export const metadata = {
  title: 'Run for Ukraine',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
      <link rel="icon" href="/favicon.ico" sizes="any"/>
    </head>
      <body>{children}</body>
    </html>
  )
}
