import {useLocale} from 'next-intl';
import {notFound} from 'next/navigation';

export const metadata = {
  title: 'Run for Ukraine',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params:any,
}) {
  const locale = useLocale();

  // Validate that the incoming `locale` parameter is a valid locale
  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang="en">
    <head>
      <link rel="icon" href="/src/app/favicon.ico" sizes="any"/>
    </head>
      <body>{children}</body>
    </html>
  )
}
